# basic
baseurl = "https://alphabeee.github.io" 
languageCode = "zh-tw" 
title = "hahahahaha" 
theme = "PaperMod" 
buildDrafts = false 

[[menu.main]]

identifier = "tags"

name = "Tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "Welecome to my blog"
subtitle = "我是Bo Hong Lin"
imageUrl = "img/R.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "是我夢到蝴蝶還是蝴蝶夢到我"
