# basic
baseurl = "https://alphabeee.github.io" 
languageCode = "zh-tw" 
title = "hahahahaha" 
theme = "PaperMod" 
buildDrafts = false 

[[menu.main]]

identifier = "tags"

name = "Tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "Welecome to my blog"
subtitle = "我是Bo Hong Lin"
imageUrl = "img/R.jpg"
imageWidth = 150
imageHeight = 150
imageTitle = "是我夢到蝴蝶還是蝴蝶夢到我"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Alphabeee"

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視

